### ISSUE TITLE
As a developer I want to be able to pull up a UGClasses object using a class id and find all registered students in it. So, we need a UGClasses object which stores this information.

### ISSUE THREAD

**Issue by eselkin** [DevSpecs/UniGamer#6]
See walkthrough slide 7 https://docs.google.com/presentation/d/1txOl760gEh8GisRGiq5wIN4R0-OVaEuq_4ZM8fAsroQ/edit?usp=sharing

**Comment by rwhere** [comment]
Completed.

**Comment by eselkin** [comment]
The UGClasses object should have three columns and be referenced by the key from the class_id.

**Comment by rwhere** [comment]
@eselkin that's what i did? check it out. it does have 3 columns. it also does use a foreign key based on class_list's primary key (class id)

**Comment by eselkin** [comment]
I don't know why it didn't pull this version earlier. I guess it was just a delay in github processing. Good work.
